"""Channel-specific response formatters."""

from production.agent.tools import Channel


def format_email_response(response: str, customer_name: str = "Customer", ticket_id: str = "") -> str:
    """Format response for email channel."""
    greeting = f"Hi {customer_name}," if customer_name else "Hi,"
    return (
        f"{greeting}\n\n"
        f"Thank you for reaching out to FlowBoard Support.\n\n"
        f"{response}\n\n"
        f"If you have any further questions, please don't hesitate to reply to this email.\n\n"
        f"Best regards,\n"
        f"FlowBoard Support Team\n"
        f"---\n"
        f"Ticket Reference: {ticket_id}\n"
        f"This response was generated by our AI assistant. "
        f"For complex issues, you can request human support."
    )


def format_whatsapp_response(response: str, max_length: int = 1600) -> list[str]:
    """Format and split response for WhatsApp (max 1600 chars per message)."""
    suffix = "\n\nReply for more help or type 'human' for live support."
    full_response = response + suffix

    if len(full_response) <= max_length:
        return [full_response]

    # Split into multiple messages
    messages = []
    remaining = response
    while remaining:
        if len(remaining) <= max_length - len(suffix):
            messages.append(remaining.strip() + suffix)
            break

        break_point = remaining.rfind(". ", 0, max_length - len(suffix))
        if break_point == -1:
            break_point = remaining.rfind(" ", 0, max_length - len(suffix))
        if break_point == -1:
            break_point = max_length - len(suffix)

        messages.append(remaining[: break_point + 1].strip())
        remaining = remaining[break_point + 1 :].strip()

    return messages


def format_web_response(response: str) -> str:
    """Format response for web form channel."""
    return (
        f"{response}\n\n"
        f"---\n"
        f"Need more help? Reply to this message or visit our support portal."
    )
